apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-devops-todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-devops-todo-api
  template:
    metadata:
      labels:
        app: nest-devops-todo-api
    spec:
      containers:
        - name: nest-devops-todo-api
          image: DOCKER_USERNAME/nest-devops-todo-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: MONGO_URI

            - name: COOKIE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: COOKIE_NAME

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: JWT_SECRET

            - name: TODO_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: TODO_API_KEY

          imagePullPolicy: Never
