apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
data:
  # To get below key ---> echo -n "superSecretJWTKey123" | base64
  JWT_SECRET: c3VwZXJTZWNyZXRKV1RLZXkxMjM= # base64 encoded
